### ISSUE TITLE
Найти html шаблон для сайта 

### ISSUE THREAD

**Issue by chuguev** [chuguev/ksu-child-template#1]
Пример дочернего сайта http://fmi.kursksu.ru/

Поискать готовые шаблоны html на сайте https://themeforest.net/ или аналогичных.

Добавить список подходящих шаблонов в раздел Wiki

**Comment by DmitriyDeveloper** [comment]
Добавил 9 шаблонов.

**Comment by DmitriyDeveloper** [comment]
Добавил еще 9, но уже бесплатных шаблонов.

**Comment by Jokerdanman777** [comment]
Топ 5 дай 5
1. https://www.templatemonster.com/ru/demo/50861.html (9)  
2. https://www.webfulcreations.com/themes/items/?theme=Education-WP (14)  
3. http://preview.themeforest.net/item/sakola-school-wordpress-theme/full_screen_preview/20630435?_ga=2.199098155.527280425.1510315045-2119585144.1510152956  (19)
4. http://demo.themeum.com/?theme=educon (26)  
5. https://justfreethemes.com/demo?theme=Graduate (36)

**Comment by ArkadiyMikhailov** [comment]
1. https://justfreethemes.com/demo?theme=Graduate

2.http://university.thimpress.com/

3. http://demo.cmssuperheroes.com/?theme=diplomia
4. http://www.nicdarkthemes.com/themes/education/wp/demo/university/

5. http://demos.themecycle.com/edupress-uni/

**Comment by ArturPravdivtsev** [comment]
1. https://themeforest.net/item/education-wordpress-theme-education-wp/14058034 (24)
2. https://twd.wordpress.org/themes/education-zone/ (34)
3. https://twd.wordpress.org/themes/university-hub/ (35)
4. http://preview.themeforest.net/item/eduonline-education-university-wordpress-theme/full_screen_preview/19942935 (2)
5. http://gt3demo.com/?theme=Wizeedu%20WP (16)

**Comment by DmitriyDeveloper** [comment]
1. http://gt3demo.com/?theme=Wizeedu%20WP (16)
2. http://university.thimpress.com/ (28)
3. http://demo.cmssuperheroes.com/?theme=diplomia (18)
4. http://preview.themeforest.net/item/sakola-school-wordpress-theme/full_screen_preview/20630435?_ga=2.199098155.527280425.1510315045-2119585144.1510152956 (19)
5. https://twd.wordpress.org/themes/university-hub/ (35)

**Comment by chuguev** [comment]
Короче наш выбор пал на http://demo.themeum.com/wordpress/educon/
